const EnvConfigVariable = {
  OAUTH2_CLIENT_ID: process.env.REACT_APP_OAUTH2_CLIENT_ID,
  OAUTH2_CLIENT_SECRET: process.env.REACT_APP_OAUTH2_CLIENT_SECRET,
  OAUTH2_REDIRECT_URI: process.env.REACT_APP_OAUTH2_REDIRECT_URI,
  OAUTH2_POST_LOGOUT_URI: process.env.REACT_APP_OAUTH2_POST_LOGOUT_URI,
  OAUTH2_SERVER_HOST: process.env.REACT_APP_OAUTH2_SERVER_HOST,
  API_BACKEND_URI: process.env.REACT_APP_API_BACKEND_URI
}

export default EnvConfigVariable
